UPSTREAM: of: add HAS_IOMEM depends to OF_ADDRESS
On UML builds, of_address.c fails to compile:

../drivers/of/address.c:873:2: error: implicit declaration of function ‘ioremap’ [-Werror=implicit-function-declaration]

This is due to CONFIG_OF now being user selectable. Add a dependency on
HAS_IOMEM to OF_ADDRESS in order to fix this.

Signed-off-by: Rob Herring <robh@kernel.org>
Cc: Grant Likely <grant.likely@linaro.org>
(cherry picked from commit 39da809e86274abbd9010365906045e02da3944a)
Bug: 70214720
Change-Id: I905b264db2d1be6996d6a044afd974c6d9e148de
Signed-off-by: Alistair Strachan <astrachan@google.com>